spring:
  application:
    name: edge-service

  data:
    redis:
      host: redis
      port: 6379

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: content-route-root
              uri: ${CONTENT_SERVICE_URL:http://content-manager}
              predicates:
                - Path=/topics
              filters:
                - SaveSession

            - id: content-route-nested
              uri: ${CONTENT_SERVICE_URL:http://content-manager}
              predicates:
                - Path=/topics/**
              filters:
                - SaveSession

            - id: progress-route-root
              uri: ${PROGRESS_SERVICE_URL:http://progress-manager}
              predicates:
                - Path=/progress
              filters:
                - SaveSession

            - id: progress-route-nested
              uri: ${PROGRESS_SERVICE_URL:http://progress-manager}
              predicates:
                - Path=/progress/**
              filters:
                - SaveSession

server:
  port: 8080
  forward-headers-strategy: framework

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
